### ISSUE TITLE
Load image error

### ISSUE THREAD

**Issue by AMYERYAN** [recleelab/dNEMO-0.9.0#1]
I'm receiving an error upon loading the image (including the sample image provided). Some things I've noted:

- User interface shows up with no apparent issues.
- Error upon loading an image, points to: $HOME\bfmatlab\loci_tools.jar which does not seem to exist (wondering if it was deleted/renamed).
- Tried to load image from your recommended sample directory (from Bio-Formats), same errors.
- Moved image around within the PATH, no difference was made. 
- Same error received regardless of Matlab version (2018, 2019, 2020).

![dnemo_error](https://user-images.githubusercontent.com/74214065/98600410-83262800-22ab-11eb-8982-cfd71b8fcd61.jpg)

**Comment by gabrieljaykay** [comment]
Thank you for bringing this issue to our attention. The 'bioformats_package.jar' was supposed to be included in this version of bfmatlab as well, but when posting the code apparently the package wasn't posted because of its size. Our image class uses some of the bioformats java functions to read images/metadata into MATLAB. Download the 'bioformats_package.jar' from the [OME Downloads page ](https://www.openmicroscopy.org/bio-formats/downloads/) and copy it to the bfmatlab folder and the sample images will be able to be opened up without error. Will add documentation to the READ_ME to highlight this workaround and ensure that our image class is compatible with both the bioformats version we've included with dNEMO and the most recent version available on OME's website, as the version included in dNEMO may be a bit dated.
